# -*- coding: utf-8 -*-
"""tds.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/maklaa/eae4428e4668f80bff91fbfcabf01539/tds.ipynb
"""

!pip install streamlit
import streamlit as st
import numpy as np

st.write("Multiplication of Two Numbers")
a = st.number_input("Input First Number")
b = st.number_input("Input Second Number")
c = np.multiply(a,b)
st.subheader("Multiplication of two numbers is")
st.write(c)